# This is the configuration used to check the rubocop source code.

Style/Encoding:
  Enabled: true

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/LineLength:
  Max: 132

Metrics/MethodLength:
  Max: 24

Metrics/ClassLength:
  Max: 140

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Enabled: false

